### ISSUE TITLE
UTM == ENU ?

### ISSUE THREAD

**Issue by mescarra** [bsb808/geonav_transform#1]
Hello, I was wondering if in this package UTM coordinates are perfectly aligned with ENU. I have read [here](https://bitbucket.org/DataspeedInc/oxford_gps_eth/issues/5/about-velocity-in-utm) that they differ due to convergence (true north vs grid north) but since you assume the orientation is true, the published  coordinate system could be perfectly aligned to ENU.

Can you confirm this?

**Comment by bsb808** [comment]
Very good question.  The attitude estimate, coming from the sensor, is in ENU (see http://wiki.ros.org/geonav_transform#geoodom).  The transform to UTM and local coordinates is only really a translational mapping (converting lat/lon/alt to an x/y/z in UTM or local), then the orientation that is reported is in ENU.

The sensors we typically use report this orientation based on true north, so the published odometry messages would include a an orientation in ENU - not grid north.

Does this have a large consequence for your use case?

**Comment by mescarra** [comment]
No, that's ok. Thank you very much for your quick response!

**Comment by jasonbeach** [comment]
Just as an FYI for anyone else who might see this, in general ENU (or NED) and UTM are not aligned. Grid convergence mentioned above is the biggest issue (formula for calculating is [here](https://gis.stackexchange.com/a/147527/98340)) From that you can see that if the reference point of the ENU frame is on a central meridian of the UTM zone or at the equator then grid convergence is zero. 

Even in that case or if you rotate the ENU frame by the grid convergence, there appears to still be some distortion to where the two aren't a perfect match up.  I'm casting a line-of sight vector generated in an NED frame over about 2km to intersect with a DEM that is in UTM coordinates. Over 2km there isl < 1m error which is ok for what I need but from there it starts to get kind of big fast.

If your areas are much smaller then it's an ok assumption (although I'd still include grid convergence in any transform calculations)

**Comment by bsb808** [comment]
This is a good description of the issue.  Are you able to include grid convergence in your transform calculations?  Since this does come up every once in awhile.  It would be interesting to have a PR to modify the transforms.
