### ISSUE TITLE
alvinxy algorithm

### ISSUE THREAD

**Issue by goldminenine** [bsb808/geonav_transform#5]
Hi,
the below subprogram of the alvinxy.py source looks incorrect compared to the following document: http://www.chrismurf.com/papers/auv10-navigation.pdf

```
def mdeglon(lat):
    '''
    Provides meters-per-degree longitude at a given latitude
    Args:
      lat (float): latitude in decimal degrees
    Returns:
      float: meters per degree longitude
    '''
    latrad = lat*2.0*pi/360.0 
    dx = 111415.13 * cos(latrad) \
         - 94.55 * cos(3.0*latrad) \
	+ 0.12 * cos(5.0*latrad)
    return dx
```

The correct line would be (see the operator before 0.12)

```
 dx = 111415.13 * cos(latrad) \
       - 94.55 * cos(3.0*latrad) \
       - 0.12 * cos(5.0*latrad) 
```

**Comment by layssi** [comment]
Any update on this??

**Comment by bsb808** [comment]
I'd have to dig up the original reference to verify that we have the sign correct.  I found it in Bowditch many years ago, but don't have it on hand at the moment.

Regardless, the last term is very small - it really should probably be neglected.   See two images below to quantify the difference.

![fig1](https://user-images.githubusercontent.com/8921143/142969762-70d70dd7-03b8-4876-9357-413a9da0dedb.png)
![fig2](https://user-images.githubusercontent.com/8921143/142969776-303e66dd-6085-4772-8e9a-0b9ea4f608d9.png)
